version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Install Node.js and npm
          command: |
            apt-get update
            apt-get install -y nodejs npm

      - run:
          name: Install Netlify CLI
          command: |
            npm install -g netlify-cli@latest --unsafe-perm=true --allow-root

      - persist_to_workspace:
          root: /app
          paths:
            - .

  test:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-report/test-results.xml

  deploy:
    docker:
      - image: node:14

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Deploy to Netlify
          command: |
            netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN -d .

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
