version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest

      - persist_to_workspace:
          root: /app
          paths:
            - models/

  deploy:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Deploy to Production
          command: |
            # Add deployment commands here
            # e.g., streamlit run your_app.py


  store_test_results:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Store Test Results
          command: |
            mkdir -p /app/test-report
            mv /app/test-results.txt /app/test-report/
            echo "Found some test results!" > /app/test-report/test-results-info.txt

      - store_test_results:
          path: /app/test-report

  store_artifacts:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Store Artifacts
          command: |
            mkdir -p /app/artifacts
            mv /app/artifacts/dummy.txt /app/artifacts/
            echo "Stored some artifacts!" > /app/artifacts/artifacts-info.txt

      - store_artifacts:
          path: /app/artifacts


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                
      - store_test_results:
          requires:
            - build
      - store_artifacts:
          requires:
            - deploy

