version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

       # List files in the directory
      - run:
          name: List Files
          command: ls -l

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v tests --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

      # Save artifacts (model.pkl)
      - persist_to_workspace:
          root: .
          paths:
            - models

  deploy:
    docker:
      - image: python:3.8

    steps:
      - attach_workspace:
          at: /workspace


      # Check if requirements.txt exists
      - run:
          name: Check Requirements.txt
          command: test -e requirements.txt || (echo "File not found" && exit 1)

      # Install dependencies (adjust as needed)
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Deploy Streamlit app (adjust as needed)
      - run:
          name: Deploy Streamlit App
          command: |
            streamlit run main.py 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
