version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      
  deploy:
    docker:
      - image: pulumi/pulumi:latest

    steps:
      - checkout

      # Install Pulumi CLI
      - run:
          name: Install Pulumi CLI
          command: |
            curl -fsSL https://get.pulumi.com | sh

      # Login to Pulumi
      - run:
          name: Login to Pulumi
          command: |
            pulumi login
            pulumi stack select your_stack_name

      # Deploy with Pulumi
      - run:
          name: Deploy with Pulumi
          command: |
            pulumi up --yes

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
