name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install

    - name: Run tests
      run: |
        pytest --junitxml=test-report/test-results.xml
        # Add other test commands as needed


    - name: Deploy to GitHub Pages
      run: |
        echo "Deploying to GitHub Pages"
        gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
        gh pages --dist coverage_html --add

